### ISSUE TITLE
Cannot import large contact lists

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#127] opened 2019-08-26 06:12 UTC
If you try importing a large contact list (not sure about the exact required minimum, I tested with 1000 contacts), the import process will always fail with the following error:

![import large contact list](https://user-images.githubusercontent.com/44697797/63668994-15422d80-c7d9-11e9-9634-b8dc4e45dcec.jpg)

**Steps to reproduce:**

1. Download sample file
2. Import it into the contacts app
3. Wait for the import process to reach 100%
4. Notice the console error

**Sample file:**

Contact me

**Comment by dhoko** [comment] 2019-08-29 16:01
test

**Comment by econdepe** [comment] 2019-09-06 15:58
I could not reproduce the exact screen in the issue, but I did get the TimeoutError with the big list of contacts. This bug should be fixed by #143.

![image](https://user-images.githubusercontent.com/33841139/64442338-e331a500-d0cf-11e9-80a4-8ccdc0dfa0ab.png)

**Closed** 2019-09-13 14:28 UTC
Labels: bug
