### ISSUE TITLE
Advanced contact editor table is not responsive

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#254] opened 2019-10-24 07:22 UTC
**Summary:**

The PGP table in the advanced contact editor is not responsive, which is why columns are overlapping each other.

**Example:**

![Screenshot_8](https://user-images.githubusercontent.com/44697797/67462325-9c781a00-f63f-11e9-9fec-404f3e5d5130.png)

**Env:**

Chrome desktop set in mobile device mode

**Comment by EpokK** [comment] 2019-10-24 07:41
We can hide `created` and `type` columns on mobile.

**Comment by mmso** [comment] 2019-10-24 07:47
We should have that here too @econdepe

**Comment by econdepe** [comment] 2019-12-01 23:52
Addressed in #338:

![image](https://user-images.githubusercontent.com/33841139/69922589-e1dd0200-149d-11ea-8b45-1cbaa1ab6bc3.png)

![image](https://user-images.githubusercontent.com/33841139/69922603-f4573b80-149d-11ea-9902-da9fd9138690.png)

**Comment by DeepSpaceHarbor** [comment] 2019-12-02 13:44
**Summary**
Part of the dropdown button is hidden. is this expected behavior?

![image](https://user-images.githubusercontent.com/11393457/69964149-125e8380-1512-11ea-96c6-6f1ac0dfaa93.png)

**Comment by DeepSpaceHarbor** [comment] 2019-12-02 13:45
**Summary**
If possible, we should add some spacing between the text and the upload button.

![image](https://user-images.githubusercontent.com/11393457/69964258-52be0180-1512-11ea-920e-3f6b287431c8.png)

**Comment by econdepe** [comment] 2019-12-02 13:46
Isn't it possible to scroll right to see the full button? At any rate that doesn't look too ideal

**Comment by DeepSpaceHarbor** [comment] 2019-12-02 13:55
@econdepe yes, the user can scroll and use the button. I mentioned it, because the button looks a bit out of place.

**Comment by econdepe** [comment] 2019-12-03 10:30
It's not easy to handle columns properly on mobile view, but some changed have been introduced into the code to improve it a bit

**Closed** 2019-12-17 15:32 UTC
Labels: Bug, Good first issue, P4: Medium
