### ISSUE TITLE
'No csv or vcard file selected' error message when importing contacts

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#60] opened 2019-07-31 19:59 UTC
If you select any vcf or csv file, the import process is going to fail with the same error message: `no .csv or .vcard file selected`.

**Steps to reproduce:**

1. Click on import in contacts
2. Select any csv or vcf file
3. Notice the error and failed import process

**Screenshot:**

![import failed](https://user-images.githubusercontent.com/44697797/62243792-56b00a80-b3de-11e9-8123-e14e055406dc.jpg)

**Comment by econdepe** [comment] 2019-08-05 14:23
It seems this bug depends on the OS because I was unable to see it in Linux (Apple and Microsoft should learn how store csv and vcf files... ;P).

**Comment by emnproton** [comment] 2019-08-05 18:55
@econdepe I'm using Windows 10 x64 with Chrome 76 if it helps. The same issue happens on Win 7 too.

**Comment by econdepe** [comment] 2019-08-05 21:29
Hey @emnproton ! Yeah, Richard and Mattias could also reproduce it in MacOS systems. It's just in Linux that you one can't find it. Anyway, it's fixed now! Thanks for pointing it out!

**Comment by emnproton** [comment] 2019-08-22 07:54
I can still reproduce the issue (inc. on macOS).

**Closed** 2019-08-22 08:36 UTC
Labels: bug, high
